#.travis.yml

language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - master

before_script:
  - npm i -g angular-cli-ghpages
  - npm install -g @angular/cli

script:
  - node md-treeview.js
  - ng build --prod --base-href "https://rajkeshwar.github.io/docs/"

after_success:
  - ngh --repo=https://GH_TOKEN@github.com/rajkeshwar/docs.git

notifications:
  email:
    on_failure: change
    on_success: change